// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package memory

import (
	"database/sql"

	"github.com/google/uuid"
)

type Url struct {
	ID            uuid.UUID
	OriginalUrl   string
	ShortenedCode string
	CreatedAt     sql.NullTime
}
