// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package memory

import (
	"context"
)

const createUrl = `-- name: CreateUrl :exec
INSERT INTO urls (shortened_code, original_url)
VALUES ($1, $2)
`

type CreateUrlParams struct {
	ShortenedCode string
	OriginalUrl   string
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) error {
	_, err := q.db.ExecContext(ctx, createUrl, arg.ShortenedCode, arg.OriginalUrl)
	return err
}

const getUrl = `-- name: GetUrl :one
SELECT original_url FROM urls
WHERE shortened_code = $1
`

func (q *Queries) GetUrl(ctx context.Context, shortenedCode string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUrl, shortenedCode)
	var original_url string
	err := row.Scan(&original_url)
	return original_url, err
}
